### ISSUE TITLE
Not released

### ISSUE THREAD

**Issue by pstubbs1020** [bsas/bfrpg#1]
Came across your BFRPG repository for Foundry and tried to install it but got the error of no download url provided for the system json. Tried the manual install but it says there is no release page. Is this a private BFRPG system for the creator's personal use?

**Comment by bsas** [comment]
The system is not done at all. I started working on it a while ago but life got in the way. I still plan to do it but not sure when, sorry :(

**Comment by dfeg** [comment]
Hey bsas, I understand your pain. I started myself but life also got in the way. If you need a hand with this, even if its just creating compendiums let me know. Would love to have BFRPG on foundry but understand the amount of work.

**Comment by bsas** [comment]
For everyone interested, someone else did it and it looks really good: https://github.com/orffen/basicfantasyrpg
